### ISSUE TITLE
Output is missing commas

### ISSUE THREAD

**Issue by baileyandy** [sergaben/NumberConverter#3]
For the input `78949`, I would expect the application to produce the output

> seventy eight thousand, nine hundred and forty nine

instead of the current output of

> seventy eight thousand and nine hundred and forty nine

**Comment by sergaben** [comment]
Hi @baileyandy , I will make sure to solve this issue.
Any extra details that you might want to share about the root of the bug I will gladly appreciate it.

**Comment by sergaben** [comment]
Hi @baileyandy , I have just solved this issue
