### ISSUE TITLE
Logic optimisation

### ISSUE THREAD

**Issue by baileyandy** [sergaben/NumberConverter#4]
For the following code:

https://github.com/sergaben/NumberParser/blob/e82570aafc3f21f0911ff5802a93f8294411c576/src/main/scala/Logic/Parser.scala#L54

https://github.com/sergaben/NumberParser/blob/e82570aafc3f21f0911ff5802a93f8294411c576/src/main/scala/Logic/Parser.scala#L71

https://github.com/sergaben/NumberParser/blob/e82570aafc3f21f0911ff5802a93f8294411c576/src/main/scala/Logic/Parser.scala#L107

the internal logic is very similar. I think there is some optimisation to be found here by reusing generic logic to convert a set of 3 numbers into words.

For example 356, 356000 and 356000000 have the same initial output - only the magnitude is different (nothing, thousand and million)

**Comment by sergaben** [comment]
I have tried to optimize it and I have pushed the changes that I made, however I think there is a better way of doing the logic but I can't think of a way to accomplish that

**Comment by sergaben** [comment]
I fixed most of the duplication logic, however there is still room for improvement
Let me know if there is anything else I could improve. I am closing the issue.
